"""initial schema

Revision ID: 0001_initial
Revises: None
Create Date: 2026-03-27 00:00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email_optional", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Enum("participant", "reviewer", "administrator", name="role_enum"), nullable=False),
        sa.Column("status", sa.Enum("active", "disabled", name="user_status_enum"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("force_password_change", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("captcha_required", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    for table_name in [
        "password_history",
        "refresh_tokens",
        "notification_preferences",
        "participant_profile_versions",
        "participant_profiles",
        "nutrition_plan_versions",
        "nutrition_plans",
        "plan_phases",
        "review_assignments",
        "declaration_packages",
        "package_versions",
        "declaration_state_history",
        "correction_requests",
        "delivery_files",
        "download_tokens",
        "acceptance_confirmations",
        "notifications",
        "mentions",
        "field_mappings",
        "masking_policies",
        "import_jobs",
        "export_jobs",
        "audit_logs",
        "scheduler_job_runs",
        "system_settings",
    ]:
        pass

    op.create_table("password_history", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("password_hash", sa.String(length=255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("refresh_tokens", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(length=255), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True), sa.Column("rotated_from_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("refresh_tokens.id"), nullable=True), sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True), sa.Column("user_agent", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.create_table("notification_preferences", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("status_changes_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("mentions_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("review_requests_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("deadline_warnings_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id"))
    op.create_table("participant_profile_versions", sa.Column("profile_id", postgresql.UUID(as_uuid=True), nullable=True), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("snapshot_json", sa.JSON(), nullable=False), sa.Column("change_summary_json", sa.JSON(), nullable=False), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("participant_profiles", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("profile_status", sa.String(length=50), nullable=False), sa.Column("demographics_json", sa.JSON(), nullable=False), sa.Column("medical_flags_json", sa.JSON(), nullable=False), sa.Column("activity_json", sa.JSON(), nullable=False), sa.Column("anthropometrics_json", sa.JSON(), nullable=False), sa.Column("encrypted_payload", sa.Text(), nullable=True), sa.Column("current_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("participant_profile_versions.id"), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id"))
    op.create_foreign_key(None, "participant_profile_versions", "participant_profiles", ["profile_id"], ["id"], ondelete="CASCADE")
    op.create_table("nutrition_plan_versions", sa.Column("plan_id", postgresql.UUID(as_uuid=True), nullable=True), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("summary", sa.Text(), nullable=True), sa.Column("phase_count", sa.Integer(), nullable=False), sa.Column("snapshot_json", sa.JSON(), nullable=False), sa.Column("change_summary_json", sa.JSON(), nullable=False), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("nutrition_plans", sa.Column("participant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("participant_profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(length=255), nullable=False), sa.Column("duration_weeks", sa.Integer(), nullable=False), sa.Column("goal_category", sa.String(length=100), nullable=False), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("current_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("nutrition_plan_versions.id"), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_foreign_key(None, "nutrition_plan_versions", "nutrition_plans", ["plan_id"], ["id"], ondelete="CASCADE")
    op.create_table("plan_phases", sa.Column("plan_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("nutrition_plan_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("phase_number", sa.Integer(), nullable=False), sa.Column("week_start", sa.Integer(), nullable=False), sa.Column("week_end", sa.Integer(), nullable=False), sa.Column("objective", sa.Text(), nullable=False), sa.Column("calorie_target", sa.Integer(), nullable=True), sa.Column("macro_targets_json", sa.JSON(), nullable=False), sa.Column("habits_json", sa.JSON(), nullable=False), sa.Column("success_metrics_json", sa.JSON(), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("review_assignments", sa.Column("package_id", postgresql.UUID(as_uuid=True), nullable=True), sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False), sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=False), sa.Column("priority", sa.String(length=50), nullable=False), sa.Column("status", sa.Enum("queued", "in_review", "completed", "reassigned", "cancelled", name="review_assignment_status_enum"), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("declaration_packages", sa.Column("package_number", sa.String(length=50), nullable=False), sa.Column("participant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("participant_profiles.id"), nullable=False), sa.Column("plan_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("nutrition_plans.id"), nullable=False), sa.Column("current_plan_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("nutrition_plan_versions.id"), nullable=True), sa.Column("current_profile_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("participant_profile_versions.id"), nullable=True), sa.Column("state", sa.Enum("draft", "submitted", "withdrawn", "corrected", "voided", name="declaration_state_enum"), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True), sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True), sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True), sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True), sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True), sa.Column("current_review_assignment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("review_assignments.id"), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f("ix_declaration_packages_package_number"), "declaration_packages", ["package_number"], unique=True)
    op.create_foreign_key(None, "review_assignments", "declaration_packages", ["package_id"], ["id"], ondelete="CASCADE")
    op.create_table("package_versions", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("state", sa.Enum("draft", "submitted", "withdrawn", "corrected", "voided", name="package_version_state_enum"), nullable=False), sa.Column("profile_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("participant_profile_versions.id"), nullable=True), sa.Column("plan_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("nutrition_plan_versions.id"), nullable=True), sa.Column("snapshot_json", sa.JSON(), nullable=False), sa.Column("change_summary_json", sa.JSON(), nullable=False), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("declaration_state_history", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("from_state", sa.String(length=50), nullable=True), sa.Column("to_state", sa.String(length=50), nullable=False), sa.Column("reason_code", sa.String(length=100), nullable=True), sa.Column("reason_text", sa.Text(), nullable=True), sa.Column("changed_by", sa.String(length=255), nullable=True), sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("correction_requests", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("review_assignment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("review_assignments.id", ondelete="CASCADE"), nullable=False), sa.Column("requested_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False), sa.Column("response_due_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.Enum("open", "acknowledged", "resubmitted", "closed", name="correction_status_enum"), nullable=False), sa.Column("sections_json", sa.JSON(), nullable=False), sa.Column("overall_message", sa.Text(), nullable=False), sa.Column("participant_acknowledged_at", sa.DateTime(timezone=True), nullable=True), sa.Column("participant_resubmitted_at", sa.DateTime(timezone=True), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("delivery_files", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("file_type", sa.String(length=100), nullable=False), sa.Column("display_name", sa.String(length=255), nullable=False), sa.Column("storage_path", sa.Text(), nullable=False), sa.Column("mime_type", sa.String(length=100), nullable=False), sa.Column("checksum_sha256", sa.String(length=64), nullable=False), sa.Column("size_bytes", sa.Integer(), nullable=False), sa.Column("version_label", sa.String(length=100), nullable=True), sa.Column("is_final", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("download_tokens", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("delivery_file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("delivery_files.id", ondelete="CASCADE"), nullable=False), sa.Column("issued_to_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(length=255), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True), sa.Column("used_at", sa.DateTime(timezone=True), nullable=True), sa.Column("issued_by", sa.String(length=255), nullable=True), sa.Column("purpose", sa.String(length=100), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index(op.f("ix_download_tokens_token_hash"), "download_tokens", ["token_hash"], unique=True)
    op.create_table("acceptance_confirmations", sa.Column("package_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("declaration_packages.id", ondelete="CASCADE"), nullable=False), sa.Column("confirmed_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False), sa.Column("confirmation_note", sa.Text(), nullable=True), sa.Column("accepted_delivery_version", sa.String(length=100), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("notifications", sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(length=100), nullable=False), sa.Column("severity", sa.String(length=50), nullable=False), sa.Column("title", sa.String(length=255), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("link_path", sa.String(length=255), nullable=True), sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("is_muted_snapshot", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("mentions", sa.Column("notification_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("notifications.id", ondelete="CASCADE"), nullable=False), sa.Column("source_type", sa.String(length=100), nullable=False), sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("mentioned_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("mentioned_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("field_mappings", sa.Column("name", sa.String(length=255), nullable=False), sa.Column("entity_type", sa.String(length=100), nullable=False), sa.Column("format", sa.String(length=20), nullable=False), sa.Column("mapping_json", sa.JSON(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("masking_policies", sa.Column("name", sa.String(length=255), nullable=False), sa.Column("entity_type", sa.String(length=100), nullable=False), sa.Column("rules_json", sa.JSON(), nullable=False), sa.Column("is_default", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("created_by", sa.String(length=255), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("import_jobs", sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("format", sa.String(length=20), nullable=False), sa.Column("source_file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("delivery_files.id"), nullable=True), sa.Column("mapping_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("field_mappings.id"), nullable=True), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("row_count", sa.Integer(), nullable=False), sa.Column("success_count", sa.Integer(), nullable=False), sa.Column("failure_count", sa.Integer(), nullable=False), sa.Column("checksum_sha256", sa.String(length=64), nullable=True), sa.Column("started_at", sa.DateTime(timezone=True), nullable=True), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.Column("error_report_path", sa.Text(), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("export_jobs", sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("format", sa.String(length=20), nullable=False), sa.Column("scope_type", sa.String(length=100), nullable=False), sa.Column("masking_policy_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("masking_policies.id"), nullable=True), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("row_count", sa.Integer(), nullable=False), sa.Column("checksum_sha256", sa.String(length=64), nullable=True), sa.Column("output_file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("delivery_files.id"), nullable=True), sa.Column("started_at", sa.DateTime(timezone=True), nullable=True), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("audit_logs", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True), sa.Column("action_type", sa.String(length=100), nullable=False), sa.Column("entity_type", sa.String(length=100), nullable=False), sa.Column("entity_id", sa.String(length=100), nullable=False), sa.Column("ip_address", sa.String(length=64), nullable=True), sa.Column("request_id", sa.String(length=100), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=False), sa.Column("previous_hash", sa.Text(), nullable=True), sa.Column("entry_hash", sa.Text(), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("scheduler_job_runs", sa.Column("job_name", sa.String(length=100), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True), sa.Column("status", sa.String(length=50), nullable=False), sa.Column("details_json", sa.JSON(), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_table("system_settings", sa.Column("key", sa.String(length=100), nullable=False), sa.Column("value_json", sa.JSON(), nullable=False), sa.Column("updated_by", sa.String(length=255), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True))
    op.create_index(op.f("ix_system_settings_key"), "system_settings", ["key"], unique=True)


def downgrade() -> None:
    for table in [
        "system_settings", "scheduler_job_runs", "audit_logs", "export_jobs", "import_jobs", "masking_policies", "field_mappings",
        "mentions", "notifications", "acceptance_confirmations", "download_tokens", "delivery_files", "correction_requests",
        "declaration_state_history", "package_versions", "declaration_packages", "review_assignments", "plan_phases",
        "nutrition_plans", "nutrition_plan_versions", "participant_profiles", "participant_profile_versions",
        "notification_preferences", "refresh_tokens", "password_history", "users",
    ]:
        op.drop_table(table)
